# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package test and build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: [linux, self-hosted]
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8","3.11", "3.12"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install hatchling

        
    - name: Lint and format check
      run: |
        # stop the build if there are Python syntax errors or undefined names
        hatch env run -e style syntax

    - name: Test with pytest
      run: |
        hatch env run -e test run-coverage 