# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: [linux, self-hosted]
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: 'pip'
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install hatchling
      - name: Test with pytest
      run: |
        hatch test -a -c
    - name: Lint and format check
      run: |
        # stop the build if there are Python syntax errors or undefined names
        hatch env run -e style syntax
